//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Container_Example.ContactServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCF_Container_Example")]
    [System.SerializableAttribute()]
    public partial class ContactViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactServiceReference.IContactsService")]
    public interface IContactsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/GetContacts", ReplyAction="http://tempuri.org/IContactsService/GetContactsResponse")]
        WCF_Container_Example.ContactServiceReference.ContactViewModel[] GetContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/GetContacts", ReplyAction="http://tempuri.org/IContactsService/GetContactsResponse")]
        System.Threading.Tasks.Task<WCF_Container_Example.ContactServiceReference.ContactViewModel[]> GetContactsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactsServiceChannel : WCF_Container_Example.ContactServiceReference.IContactsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsServiceClient : System.ServiceModel.ClientBase<WCF_Container_Example.ContactServiceReference.IContactsService>, WCF_Container_Example.ContactServiceReference.IContactsService {
        
        public ContactsServiceClient() {
        }
        
        public ContactsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Container_Example.ContactServiceReference.ContactViewModel[] GetContacts() {
            return base.Channel.GetContacts();
        }
        
        public System.Threading.Tasks.Task<WCF_Container_Example.ContactServiceReference.ContactViewModel[]> GetContactsAsync() {
            return base.Channel.GetContactsAsync();
        }
    }
}
